<?php

namespace app\admin\controller;

use helper\Recursion;
use think\Controller;
use think\facade\Request;
use app\common\model\Menu;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $nodes = Menu::where('status', 1)->order('sort', 'asc')->all()->toArray();

        $active = $this->currentNode($nodes);
        $menu = Recursion::createMenu($active, $nodes);

        $this->assign('menu', $menu);
    }

    /**
     * 当前菜单
     * @param $nodes
     * @return array
     */
    private function currentNode($nodes)
    {
        $path = Request::path();

        $index = array_search($path, array_column($nodes, 'route'));

        $arr = Recursion::getParents($nodes, $nodes[$index]['id']);

        return array_column($arr, 'id');
    }
}
