<?php

namespace app\admin\controller;

use helper\Recursion;
use think\auth\Auth;
use think\Controller;
use think\facade\Request;
use app\common\model\Menu;

class Base extends Controller
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        /*$controller = request()->controller();
        $action = request()->action();
        $auth = new Auth();
        if(!$auth->check($controller . '-' . $action, session('uid'))){
            $this->error('你没有权限访问');
        }*/

        $nodes = Menu::where('status', 1)->order('sort', 'asc')->all()->toArray();

        $crumb = $this->crumb($nodes);
        $active = array_column($crumb, 'id');
        $menu = Recursion::createMenu($active, $nodes);

        $this->assign('menu', $menu);
        $this->assign('crumb', $crumb);
    }

    /**
     * 面包屑
     * @param $nodes
     * @return array
     */
    private function crumb($nodes)
    {
        $path = Request::path();

        $index = array_search($path, array_column($nodes, 'route'));

        return Recursion::getParents($nodes, $nodes[$index]['id']);
    }
}
